config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#main'

  get '/admin' => 'admin#index'
  post '/admin/set_rate' => 'admin#set_rate'

  mount Sidekiq::Web => '/sidekiq', as: :sidekiq
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rate.rb
class Rate < ApplicationRecord
  validates :value, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :from, presence: true
  validates :to, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @rates = Rate.order(created_at: :desc)
  end

  def set_rate
    value = rate_params[:value].to_f
    expired_date = parse_expired_date(rate_params)

    setter = ManualSetter.new
    setter.call(value, expired_date)
  end

  private
    def rate_params
      params.require(:rate).permit(:value, :expired_date)
    end

    def parse_expired_date(params)
      arr = 
      [
        params['expired_date(1i)'], # год 
        params['expired_date(2i)'], # месяц
        params['expired_date(3i)'], # число
        params['expired_date(4i)'], # часы
        params['expired_date(5i)']  # минуты
      ].map(&:to_i)
      
      DateTime.new(*arr)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<div class="container">
  <div class="row row-cols-3">
    <div class="row col"></div>
    <div class="row col">
      <%= form_with url: admin_set_rate_path, method: :post, scope: :rate do |form| %>
        <div class="form-group">
          <label>Новый курс доллара к рублю</label>
          <%= form.number_field :value, step: 0.1, min: 0, required: true, class: 'form-control' %>
        </div>
        <div class="form-group">
          <label>До: </label>
          <%= form.datetime_select :expired_date, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.submit 'Установить', class: 'btn btn-primary' %>
          <br>
          <small>После нажатия обновите страницу</small>
        </div>
      <% end %>
    </div>
    <div class="row col"></div>
  </div>
</div>

<br>
<br>

<table class="table">
  <thread>
    <tr>
      <th>Дата установки</th>
      <th>Курс</th>
      <th>Установлено в ручную</th>
      <th>До</th>
    </tr>
  </thread>
  <tbody>
  <% @rates.each do |rate| %>
    <tr>
      <td><%= rate.created_at.strftime('%d-%m-%Y %H:%M:%S') %></td>
      <td><%= "1$ = #{rate.value}₽" %></td>
      <td><%= "Да" if rate.is_manual? %></td>
      <td><%= "#{rate.expired_date&.strftime('%d-%m-%Y %H:%M:%S')}" if rate.is_manual? %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExchangeRate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>